### ISSUE TITLE
New feature discussion about assigning date related to specific status

### ISSUE THREAD

**Issue by xravian** [team888/redmine-assign_current_date-plugin#1]
Hi,
Can this plugin only assign current date to custom field when user selecting a specific status?

**Comment by hhokawa777** [comment]
Hi sorry, if need new feature, creating new plugin is better. My design
policy is  keeping each plugin as simple as possible.

In your requested feature, date should be set exact moment when user set
status, or user push save button ?
How about status chang by bulk update or background update.

2016/09/06 午前1:45 "xravian" notifications@github.com:
